// Edited from /projects/acg and content/projects/acg/index.mdx.
// Facts and documentation for the ACG project file.
export const acg = {
  title: "ACG by SLBH",
  name: "Affective Computational Geometry",
  year: "2026–ongoing",
  type: "Applied research",
  location: "New York",
  summary:
    "An applied research series that translates emotional data into shared physical experiences.",
  premise:
    "Can the emotional atmosphere of a country and the feelings of a room become something we can encounter together?",
  activation: {
    venue: "The Space, Upper West Side, NYC",
    dates: "April 28–30, 2026",
    format: "Light installation, public prompt, sensory activation",
    next: "To be announced",
  },
};

export type RecordCategory = "Installation" | "Participation" | "Concept";

export type ACGRecord = {
  id: string;
  title: string;
  category: RecordCategory;
  file: string;
  alt: string;
  caption: string;
  note: string;
  width: number;
  height: number;
};

export const records: ACGRecord[] = [
  {
    id: "01",
    title: "The proposal",
    category: "Concept",
    file: "concept",
    alt: "Storefront concept drawing with separate America and UWS color fields",
    caption: "Storefront concept drawing. Two windows establish the collective and local fields.",
    note: "The premise is spatial from the beginning: place two scales of emotional experience beside one another, where their relationship can be seen from the street.",
    width: 2000,
    height: 1600,
  },
  {
    id: "02",
    title: "A public interface",
    category: "Installation",
    file: "installation-storefront",
    alt: "Two people pass the ACG storefront, with America lit violet and UWS lit red",
    caption: "The installed storefront. American Emotions and visitor responses occupy adjacent windows.",
    note: "A national field and a local field share the same architecture. The storefront brings the computational system into everyday public space.",
    width: 2000,
    height: 1600,
  },
  {
    id: "03",
    title: "The collective field",
    category: "Installation",
    file: "installation-array-01",
    alt: "The America light array illuminating a curtain in violet and pink",
    caption: "Light array 01. The collective field generated by American Emotions.",
    note: "American Emotions interprets public data through the lab’s affective model. A color field becomes an environmental output: light.",
    width: 2000,
    height: 1600,
  },
  {
    id: "04",
    title: "The local field",
    category: "Installation",
    file: "installation-array-02",
    alt: "The UWS light array rendering the local field inside the storefront",
    caption: "Light array 02. The local field shaped by visitor responses.",
    note: "People present in the room contribute to a second field. Their responses use the same emotional and color logic, allowing the two fields to be read together.",
    width: 2000,
    height: 1600,
  },
  {
    id: "05",
    title: "An invitation to respond",
    category: "Participation",
    file: "activation-prompt",
    alt: "The printed affective prompt displayed at the ACG activation",
    caption: "The in-room prompt. Participation becomes an input to the installation.",
    note: "The installation invites a response to a simple question about feeling. The person looking at the system can also become part of it.",
    width: 2000,
    height: 1600,
  },
  {
    id: "06",
    title: "The response portal",
    category: "Participation",
    file: "portal",
    alt: "ACG response portal asking How are you feeling today?",
    caption: "The web portal through which visitors contribute their response.",
    note: "Language enters the computational system here. Responses are interpreted through emotional and color logic and contribute to the local field.",
    width: 1015,
    height: 991,
  },
  {
    id: "07",
    title: "A personal reading",
    category: "Participation",
    file: "user-output",
    alt: "A visitor’s personal output from the ACG response portal",
    caption: "A returned output. An individual response rendered as a personal field.",
    note: "The same process has an individual and a shared expression: a person receives a reading while contributing to the emotional presence of the room.",
    width: 900,
    height: 1600,
  },
  {
    id: "08",
    title: "The room as participant",
    category: "Participation",
    file: "activation-room",
    alt: "Visitors gathered in conversation inside the ACG activation",
    caption: "Inside the activation. A shared setting for encountering the research.",
    note: "The work extends beyond its light arrays. Presence, conversation, and participation make the room both the site of the research and one of its inputs.",
    width: 2000,
    height: 1600,
  },
  {
    id: "09",
    title: "Reading the difference",
    category: "Installation",
    file: "activation-alignment",
    // The source filename says alignment, but the photograph shows two different colors.
    alt: "ACG storefront at night with a blue America field and a red UWS field",
    caption: "Two fields at night. This photograph records different colors in the two windows.",
    note: "Difference is part of the reading. When the fields take the same color, the system expresses a moment of alignment between its collective and local inputs.",
    width: 2000,
    height: 1600,
  },
];

export const related = [
  { title: "American Emotions", role: "The collective input", href: "/projects/american-emotions" },
  { title: "This Is How I’m Feeling: NYC", role: "Related participatory work", href: "/projects/tihif-nyc" },
  { title: "Emotion as System", role: "The research foundation", href: "/research/emotion-as-system" },
];
