import Link from "next/link";
import { getAllProjects, findImage } from "@/lib/projects";
import { TrunkLine } from "@/components/TrunkLine";
import { FallbackImg } from "@/components/projects/convergent-grammar/FallbackImg";
import { FlowDiagram } from "@/components/projects/convergent-grammar/FlowDiagram";
import { GrammarOverlay } from "@/components/projects/convergent-grammar/GrammarOverlay";

export const metadata = {
  title: "Convergent Grammar — SLBH",
  description:
    "A computational study of latent visual grammar across portraiture and adjacent image regimes.",
};

// 3×3 hero grid — one grammar variant per cell, source image loaded if present.
const HERO_VARIANTS = [0, 1, 2, 3, 4, 5, 2, 0, 1];

export default function ConvergentGrammarPage() {
  const allProjects = getAllProjects();
  const relatedSlugs = ["american-emotions", "acg"];
  const related = relatedSlugs
    .map((s) => allProjects.find((p) => p.slug === s))
    .filter(Boolean) as (typeof allProjects)[0][];

  const asset = (base: string) => findImage("convergent-grammar", base);
  const heroCells = HERO_VARIANTS.map((variant, i) => ({
    variant,
    src: asset(`grid-${i + 1}`),
  }));
  const exampleSrc = asset("example");

  return (
    <>
      {/* ── Section 1: Header ── */}
      <section className="cg-hero">
        <div className="container-page cg-hero-inner">
          <p className="t-mono cg-kicker">PROJECT 02 / 2026 / ONGOING / NYC</p>
          <h1 className="t-display cg-title">Convergent Grammar</h1>
          <p className="cg-summary">
            A computational study of latent visual grammar across portraiture
            and adjacent image regimes.
          </p>
        </div>
        <div className="cg-trunkline">
          <TrunkLine length={110} nodePosition="top" />
        </div>
      </section>

      {/* ── Section 2: Readout strip ── */}
      <div className="hairline-t hairline-b cg-readout">
        <span className="t-mono" style={{ opacity: 0.55 }}>
          SLBH / v2.0 / PROJECTS / CONVERGENT GRAMMAR
        </span>
        <span
          className="t-label cg-readout-mid"
          style={{ opacity: 0.55, letterSpacing: "0.18em" }}
        >
          AFFECT · SYSTEMS · DATA · TIME
        </span>
        <span className="t-mono" style={{ opacity: 0.55, textAlign: "right" }}>
          STATUS: ONGOING · EST. 2026
        </span>
      </div>

      {/* ── Section 3: Hero visual — grammar grid ── */}
      <section className="cg-visual" aria-label="Grid of compositional overlays">
        <div className="cg-grid">
          {heroCells.map(({ variant, src }, i) => (
            <div key={i} className="cg-cell">
              <div className="cg-cell-bg" aria-hidden />
              {src && <FallbackImg src={src} alt="" className="cg-cell-img" />}
              <GrammarOverlay variant={variant} className="cg-overlay" />
            </div>
          ))}
        </div>
        <p className="t-mono cg-visual-note">
          TK / FINAL HERO COMPOSITION — SOURCE IMAGES W/ EXTRACTED GRAMMAR
        </p>
      </section>

      {/* ── Section 4: Editorial ── */}
      <section className="container-page cg-editorial">
        {/* Block A — QUESTION */}
        <div className="cg-block cg-block--text-left">
          <div className="cg-block-text">
            <p className="t-mono cg-block-kicker">01 / QUESTION</p>
            <h2 className="t-h2 cg-block-headline">Do images share a grammar?</h2>
            <p className="t-body cg-block-body">
              Convergent Grammar began with a narrow question about portraiture.
              Across centuries and cultures, across media, do painted portraits
              share an underlying spatial grammar, a set of compositional rules
              that show up regardless of artist, period, or style?
            </p>
            <p className="t-body cg-block-body">
              The question expanded quickly. If a grammar exists for portraits,
              what about landscapes, interiors, or garments? What about
              photographs? What about images generated by machines? The project
              now runs across modes of image making, looking for compositional
              structure that survives translation between them.
            </p>
          </div>
          <div className="cg-block-visual">
            <div className="cg-frame-wrap">
              <div className="cg-frame">
                <div className="cg-frame-bg" aria-hidden />
                {exampleSrc && (
                  <FallbackImg
                    src={exampleSrc}
                    alt="Source portrait with extracted spatial grammar overlaid in hairline vectors"
                    className="cg-frame-img"
                  />
                )}
                <GrammarOverlay variant={0} className="cg-frame-overlay" />
              </div>
              <p className="t-mono cg-frame-caption">
                PORTRAIT / EXTRACTED GRAMMAR — TK SOURCE
              </p>
            </div>
          </div>
        </div>

        {/* Block B — METHOD */}
        <div className="cg-block cg-block--diagram-left">
          <div className="cg-block-visual cg-flow-wrap">
            <FlowDiagram
              ariaLabel="Method pipeline: open corpus ingestion → genre classification → compositional extraction → latent grammar"
              stages={[
                { primary: "OPEN CORPUS", secondary: "INGESTION" },
                { primary: "GENRE", secondary: "CLASSIFICATION" },
                { primary: "COMPOSITIONAL", secondary: "EXTRACTION" },
                { primary: "LATENT", secondary: "GRAMMAR" },
              ]}
            />
          </div>
          <div className="cg-block-text">
            <p className="t-mono cg-block-kicker">02 / METHOD</p>
            <h2 className="t-h2 cg-block-headline">
              A pipeline for reading images as structure.
            </h2>
            <p className="t-body cg-block-body">
              The pipeline ingests images from open collections, classifies each
              by genre, and extracts a spatial grammar, the geometric
              relationships between figures, horizons, focal points, and
              negative space. Grammars are stored as vector primitives and
              compared across the corpus.
            </p>
            <p className="t-body cg-block-body">
              The project&rsquo;s finding so far: compositional grammar is shaped
              by the spatial problem a genre was built to solve, not by subject
              matter. A portrait grammar and a landscape grammar diverge because
              they answer different questions. A portrait grammar and a
              figure-study grammar converge because they answer the same one.
            </p>
          </div>
        </div>

        {/* Block C — SCOPE */}
        <div className="cg-block cg-block--full">
          <p className="t-mono cg-block-kicker">03 / SCOPE</p>
          <h2 className="t-h2 cg-block-headline">
            What the project looks at now.
          </h2>
          <p className="t-body cg-block-body cg-block-body--wide">
            The current active scans cover painted portraits, painted
            landscapes, garments, and interiors. Photographic portraiture and
            machine-generated portraiture are being added as a longitudinal
            follow-up, tracking how portrait grammar shifts across regimes of
            image production.
          </p>
          <p className="t-body cg-block-body cg-block-body--wide">
            There is no paper yet. The project is in its research phase. Outputs
            will be released as diagrams and, eventually, as a paper on the
            vertical longitudinal study.
          </p>
        </div>
      </section>

      {/* ── Section 5: Links ── */}
      <section className="container-page cg-links">
        {[
          { label: "ARCHIVE OF RUNS", note: "TK" },
          { label: "RELATED DIAGRAMS", note: "TK — ONCE DIAGRAMS SHIP" },
        ].map(({ label, note }, i) => (
          <div
            key={label}
            className="cg-link-row"
            style={{ borderTop: i === 0 ? "0.5px solid var(--hairline)" : undefined }}
          >
            <span
              style={{
                fontFamily: "var(--font-orbitron), sans-serif",
                fontWeight: 500,
                fontSize: 13,
                letterSpacing: "0.04em",
              }}
            >
              {label}
            </span>
            <span className="t-mono cg-link-url" style={{ opacity: 0.35 }}>
              {note}
            </span>
          </div>
        ))}
      </section>

      {/* ── Section 6: Related projects ── */}
      {related.length > 0 && (
        <section className="container-page cg-related">
          <p className="t-mono cg-related-label">RELATED PROJECTS</p>
          <div className="cg-rel-grid">
            {related.map((p) => (
              <Link
                key={p.slug}
                href={`/projects/${p.slug}`}
                className="cg-rel-card link-quiet"
              >
                <div className="cg-rel-cover">
                  {p.coverPath && (
                    <FallbackImg
                      src={p.coverPath}
                      alt={p.title}
                      style={{
                        width: "100%",
                        height: "100%",
                        objectFit: "cover",
                        display: "block",
                      }}
                    />
                  )}
                </div>
                <div className="cg-rel-meta">
                  <span
                    style={{
                      fontFamily: "var(--font-orbitron), sans-serif",
                      fontWeight: 500,
                      fontSize: 13,
                      letterSpacing: "0.02em",
                      display: "block",
                      marginBottom: 6,
                    }}
                  >
                    {p.title}
                  </span>
                  <span className="t-mono" style={{ opacity: 0.55, fontSize: 10 }}>
                    {p.year}
                  </span>
                </div>
              </Link>
            ))}
          </div>
        </section>
      )}

      {/* ── Section 7: Footer ── */}
      <section className="container-page cg-footer">
        <p className="t-body cg-footer-body">
          Convergent Grammar is in active research. Findings will be published as
          diagrams and, in time, as a longitudinal study of how compositional
          grammar holds — or breaks — across regimes of image production.
        </p>
      </section>

      <style>{`
        /* ── Hero ── */
        .cg-hero {
          min-height: 60vh;
          position: relative;
          display: flex;
          flex-direction: column;
          justify-content: flex-end;
        }
        .cg-hero-inner {
          padding-top: 80px;
          padding-bottom: 80px;
        }
        .cg-kicker {
          opacity: 0.55;
          margin: 0 0 20px;
        }
        .cg-title {
          margin: 0 0 28px;
        }
        .cg-summary {
          font-family: var(--font-inter), sans-serif;
          font-weight: 300;
          font-size: 24px;
          line-height: 1.4;
          max-width: 680px;
          opacity: 0.82;
          margin: 0;
        }
        .cg-trunkline {
          position: absolute;
          bottom: 0;
          left: 50%;
          transform: translateX(-50%);
        }

        /* ── Readout strip ── */
        .cg-readout {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 16px;
          padding: 20px var(--pad-x-mobile);
          max-width: var(--max-w);
          margin-inline: auto;
          width: 100%;
          box-sizing: border-box;
        }
        @media (min-width: 768px) {
          .cg-readout { padding: 20px var(--pad-x); }
        }
        .cg-readout-mid { display: none; }
        @media (min-width: 768px) {
          .cg-readout-mid { display: block; }
        }

        /* ── Hero visual — grammar grid ── */
        .cg-visual {
          min-height: 100vh;
          position: relative;
          overflow: hidden;
          background: var(--graphite);
        }
        .cg-grid {
          position: absolute;
          inset: 0;
          display: grid;
          grid-template-columns: repeat(3, 1fr);
          grid-template-rows: repeat(3, 1fr);
        }
        .cg-cell {
          position: relative;
          overflow: hidden;
          border-right: 0.5px solid rgba(243, 242, 242, 0.08);
          border-bottom: 0.5px solid rgba(243, 242, 242, 0.08);
        }
        .cg-cell:nth-child(3n) { border-right: none; }
        .cg-cell:nth-child(n + 7) { border-bottom: none; }
        .cg-cell-bg {
          position: absolute;
          inset: 0;
          background: var(--graphite);
        }
        .cg-cell-img {
          position: absolute;
          inset: 0;
          width: 100%;
          height: 100%;
          object-fit: cover;
          display: block;
        }
        .cg-overlay {
          position: absolute;
          inset: 0;
          width: 100%;
          height: 100%;
          display: block;
        }
        .cg-visual-note {
          position: absolute;
          left: var(--pad-x-mobile);
          bottom: 20px;
          margin: 0;
          font-size: 9px;
          letter-spacing: 0.12em;
          color: rgba(243, 242, 242, 0.4);
        }
        @media (min-width: 768px) {
          .cg-visual-note { left: var(--pad-x); }
        }

        /* ── Editorial ── */
        .cg-editorial {
          padding-top: 96px;
          padding-bottom: 96px;
          display: flex;
          flex-direction: column;
          gap: 96px;
        }
        @media (min-width: 900px) {
          .cg-editorial { gap: 120px; }
        }

        .cg-block {
          display: grid;
          grid-template-columns: 1fr;
          gap: 48px;
        }
        @media (min-width: 900px) {
          .cg-block { grid-template-columns: 1fr 1fr; gap: 80px; align-items: start; }
          .cg-block--diagram-left .cg-block-visual { order: -1; }
        }
        .cg-block--full {
          display: block;
          max-width: 640px;
        }

        .cg-block-kicker {
          opacity: 0.45;
          margin: 0 0 16px;
          font-size: 10px;
          letter-spacing: 0.12em;
        }
        .cg-block-headline {
          margin: 0 0 28px;
        }
        .cg-block-body {
          margin: 0 0 18px;
          max-width: 520px;
          line-height: 1.7;
          opacity: 0.82;
        }
        .cg-block-body--wide {
          max-width: 640px;
        }
        .cg-block-body:last-child { margin-bottom: 0; }

        /* Composition frame (Block A) */
        .cg-frame-wrap { width: 100%; }
        .cg-frame {
          position: relative;
          aspect-ratio: 4/3;
          width: 100%;
          border: 0.5px solid var(--hairline-strong);
          overflow: hidden;
        }
        .cg-frame-bg {
          position: absolute;
          inset: 0;
          background: var(--graphite);
        }
        .cg-frame-img {
          position: absolute;
          inset: 0;
          width: 100%;
          height: 100%;
          object-fit: cover;
          display: block;
        }
        .cg-frame-overlay {
          position: absolute;
          inset: 0;
          width: 100%;
          height: 100%;
          display: block;
        }
        .cg-frame-caption {
          margin: 12px 0 0;
          font-size: 9px;
          opacity: 0.45;
          letter-spacing: 0.1em;
        }

        /* Flow diagram */
        .cg-flow-wrap {
          display: flex;
          align-items: center;
          padding: 32px 0;
        }

        /* ── Links ── */
        .cg-links {
          padding-top: 0;
          padding-bottom: 80px;
        }
        .cg-link-row {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 24px;
          padding: 24px 0;
          border-bottom: 0.5px solid var(--hairline);
        }
        .cg-link-url {
          font-size: 11px;
          color: var(--ground);
          text-decoration: none;
        }

        /* ── Related ── */
        .cg-related {
          padding-top: 0;
          padding-bottom: 80px;
        }
        .cg-related-label {
          opacity: 0.45;
          margin: 0 0 32px;
          font-size: 10px;
          letter-spacing: 0.12em;
        }
        .cg-rel-grid {
          display: flex;
          gap: 24px;
          overflow-x: auto;
          padding-bottom: 8px;
        }
        .cg-rel-card {
          flex-shrink: 0;
          width: 240px;
          text-decoration: none;
          color: var(--ground);
          transition: opacity 600ms var(--ease-out);
        }
        .cg-rel-grid:has(.cg-rel-card:hover) .cg-rel-card:not(:hover) {
          opacity: 0.35;
        }
        .cg-rel-cover {
          width: 240px;
          height: 300px;
          background: var(--graphite);
          overflow: hidden;
          margin-bottom: 16px;
        }
        .cg-rel-meta { padding: 0 4px; }

        /* ── Footer copy ── */
        .cg-footer {
          padding-top: 0;
          padding-bottom: 120px;
          max-width: var(--max-w);
        }
        .cg-footer-body {
          max-width: 640px;
          line-height: 1.7;
          opacity: 0.72;
          margin: 0;
        }
      `}</style>
    </>
  );
}
