name = "field-notes-list"
main = "src/index.js"
compatibility_date = "2026-01-01"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "slbh-field-notes"

[vars]
PUBLIC_BASE = "https://pub-93524f69287d48d7a901a9d4d7a88581.r2.dev/"
